In [1]:
# generally images are represented in this format[[123,12,123,12,33],[],[]]

In [2]:
import numpy

In [3]:
n = numpy.arange(27)

In [5]:
n #numpy array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
type(n)

numpy.ndarray

In [7]:
n.reshape(3,9) #converting the single dimensional array to 2 dimensional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
n.reshape(3,3,3) #converting to three dimensional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
m = numpy.asarray([[123,12,123,12,33],[],[]]) #converting to numpy array
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [11]:
import os


In [12]:
print(os.listdir())

['.ipynb_checkpoints', 'Numpy.ipynb', 'numpy2.py', 'numpyintro.py', 'smallgray.png']


In [13]:
import cv2

In [14]:
myImage = cv2.imread("smallgray.png",1)

In [15]:
print(myImage)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [16]:
myImage #each value represents BGR values b->blue g->green r->red

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [17]:
cv2.imwrite("newsmallgray.png",myImage) #to create a new image

True

In [23]:
myImage = cv2.imread("smallgray.png",0)
myImage

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
myImage[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [20]:
myImage[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [21]:
myImage.shape

(3, 5)

182

In [24]:
for i in myImage:
    print (i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [25]:
for i in myImage.flat:

SyntaxError: unexpected EOF while parsing (<ipython-input-25-a50d9b4bfb7b>, line 1)

In [26]:
for i in myImage.flat:
    print(i) #this prints individual values

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [27]:
myImage2 = numpy.hstack(myImage,myImage) #horizontally stacking

TypeError: hstack() takes 1 positional argument but 2 were given

In [28]:
#since hstack takes only 1 arguements. Tuple is used

In [29]:
myImage2 = numpy.hstack((myImage,myImage))

In [30]:
myImage2

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
myImage2 = numpy.vstack((myImage,myImage))#vertical stacking

In [32]:

#horizontal splitting
lst = numpy.hsplit(myImage2,5) #does split into different numpyarray

In [33]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [34]:
lst = numpy.vsplit(myImage2,3)

In [35]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]